version: '2'
services:
  node-app:
    # container_name: express-node-app-container
    image: hamedosama/learning-docker
    # build: .
    env_file:
      - ./.env
    # ports:
    #   - "4000:4000"
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo-db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
  redis:
    image : redis
  nginx:
    image: nginx:stable-alpine
    ports:
    - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node-app
volumes:
  mongo-db: